// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using BigTed;
using Foundation;
using UIKit;

namespace Bullbucks
{
	public partial class BalViewCtrl : UIViewController
	{
		public BalViewCtrl (IntPtr handle) : base (handle)
		{
		}

		/// <summary>
		/// Updates Balance.
		/// </summary>
		public void UpdateData()
		{
			/// Check if Card Number saved.
			if (!String.IsNullOrEmpty (KeyStore.CardNumber)) {
				/// Check if there's UID to use.
				if (!String.IsNullOrEmpty (KeyStore.UID)) {
					UIApplication.SharedApplication.NetworkActivityIndicatorVisible = true;
					InvokeInBackground (async delegate {
						var bal = await Api.GetBalance(KeyStore.CardNumber, KeyStore.UID);
						InvokeOnMainThread(delegate {
							if (bal >= 0) {
								KeyStore.Updated = DateTime.UtcNow;
								KeyStore.Balance = bal;

								this.balLbl.Text = KeyStore.Balance.ToString("C");
								this.timeLbl.Text =  KeyStore.Updated.ToString("G");
							} else {
								BTProgressHUD.ShowErrorWithStatus("Error");
							}
							UIApplication.SharedApplication.NetworkActivityIndicatorVisible = false;
						});
					});
				}
				/// Check if there's First/Lat name to use instead.
				else if (!String.IsNullOrEmpty (KeyStore.FirstName) && !String.IsNullOrEmpty (KeyStore.LastName)) {
					UIApplication.SharedApplication.NetworkActivityIndicatorVisible = true;
					InvokeInBackground (async delegate {
						var bal = await Api.GetBalance(KeyStore.CardNumber, KeyStore.FirstName, KeyStore.LastName);
						InvokeOnMainThread(delegate {
							if (bal >= 0) {
								KeyStore.Updated = DateTime.UtcNow;
								KeyStore.Balance = bal;

								this.balLbl.Text = KeyStore.Balance.ToString("C");
								this.timeLbl.Text =  KeyStore.Updated.ToString("G");
							} else {
								BTProgressHUD.ShowErrorWithStatus("Error");
							}
							UIApplication.SharedApplication.NetworkActivityIndicatorVisible = false;
						});
					});
				} else {
					BTProgressHUD.ShowErrorWithStatus ("Settings");
				}
			} else {
				BTProgressHUD.ShowErrorWithStatus ("Settings");
			}
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			/// Settings Navigation Button Clicked
			this.NavigationItem.LeftBarButtonItem.Clicked += (sender, e) => {
				this.NavigationController.PushViewController(new SettingsViewCtrl(), true);
			};

			/// Refresh Navigation Button Clicked
			this.NavigationItem.RightBarButtonItem.Clicked += (sender, e) => {
				this.UpdateData ();
			};
		}

		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);
			this.balLbl.Text = KeyStore.Balance.ToString("C");
			if (KeyStore.Updated == new DateTime (1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)) {
				this.timeLbl.Text = "Never Updated";
			} else {
				this.timeLbl.Text = KeyStore.Updated.ToString ("G");
			}

			this.UpdateData ();
		}
	}
}
