// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Bullbucks
{
	public partial class BalViewCtrl : UIViewController
	{
		public BalViewCtrl (IntPtr handle) : base (handle)
		{
		}
	}
}
